class Service {
  _key = 'df165f3a240d866ceb8f3750af9bbec1';
  BASE_URL = 'https://api.themoviedb.org/3/';

  getData = async (value, page) => {
    const url = `${this.BASE_URL}search/movie?api_key=${this._key}&query=${value || 'return'}&page=${page || '1'}`;
    const response = await fetch(url);
    if (response.ok) {
      const movies = await response.json();
      return movies;
    } else {
      throw new Error(`Could not fetch ${url}, received ${response.status}`);
    }
  };

  getGenres = async () => {
    const url = `${this.BASE_URL}genre/movie/list?api_key=${this._key}`;
    const response = await fetch(url);
    if (response.ok) {
      const genres = await response.json();
      return genres;
    } else {
      throw new Error(`Could not fetch ${url}, received ${response.status}`);
    }
  };
}

// const data = {
//   page: 1,
//   results: [
//     {
//       adult: false,
//       backdrop_path: '/dJ52jV7HlJ9hB8kdBOnj01DllBA.jpg',
//       genre_ids: [18],
//       id: 82520,
//       original_language: 'en',
//       original_title: 'Return',
//       overview:
//         'Back from a tour of duty, Kelli struggles to find her place in her family and the rust-belt town she no longer recognizes.',
//       popularity: 10.168,
//       poster_path: '/xAuR564U2njKKcXSbfbq36rZLeA.jpg',
//       release_date: '2011-02-10',
//       title: 'Return',
//       video: false,
//       vote_average: 6.666,
//       vote_count: 1018,
//     },
//     {
//       adult: false,
//       backdrop_path: '/tu5IcNPo99rJkIgNwKZqPYQ2MiY.jpg',
//       genre_ids: [27, 14, 10749],
//       id: 403587,
//       original_language: 'en',
//       original_title: 'Return',
//       overview:
//         'After reading an article about hypnotic regression, a woman whose maternal grandfather died when she was only three years old contacts the hypnotic subject named in the article believing that he is the reincarnation of her grandfather, and hoping that she can learn the truth about how he died.',
//       popularity: 5.058,
//       poster_path: '/54QOkHWUnn3gDZKfGojPiFqTHJD.jpg',
//       release_date: '1985-10-31',
//       title: 'Return',
//       video: false,
//       vote_average: 5.463,
//       vote_count: 320,
//     },
//     {
//       adult: false,
//       backdrop_path: null,
//       genre_ids: [],
//       id: 320367,
//       original_language: 'en',
//       original_title: 'Return',
//       overview:
//         'A tale of terror. Cathy Reed has been institutionalized most of her life because of Schizophrenia, as a child her parents thought she was possessed by demons and had her exercised by priests. Medical science saw different. Now decades later Cathy is freed, relocated to her own flat and given a chance to be independent. Once alone things are not what they all seem and when her nightmares turn real she questions her state of mind before she is left to face her demons.',
//       popularity: 4.197,
//       poster_path: null,
//       release_date: '2015-01-01',
//       title: 'Return',
//       video: false,
//       vote_average: 6.048,
//       vote_count: 230,
//     },
//     {
//       adult: false,
//       backdrop_path: null,
//       genre_ids: [16],
//       id: 836466,
//       original_language: 'en',
//       original_title: 'Return',
//       overview:
//         'A single man has worked most of his life in a supermarket. One night, he unexpectedly meets with his father, and the two are faced with the question of the reasons for their separation.',
//       popularity: 4.011,
//       poster_path: null,
//       release_date: '2020-06-10',
//       title: 'Return',
//       video: false,
//       vote_average: 5.721,
//       vote_count: 165,
//     },
//     {
//       adult: false,
//       backdrop_path: null,
//       genre_ids: [],
//       id: 1086372,
//       original_language: 'hy',
//       original_title: 'Return',
//       overview:
//         'The main character of the film is an outstanding physicist who was invited to Armenia from Russia to head a lab. He comes across many troubles in his homeland, but nevertheless finds his true love there.',
//       popularity: 3.87,
//       poster_path: null,
//       release_date: '1972-07-02',
//       title: 'Return',
//       video: false,
//       vote_average: 6.448,
//       vote_count: 86,
//     },
//     {
//       adult: false,
//       backdrop_path: null,
//       genre_ids: [27],
//       id: 379862,
//       original_language: 'en',
//       original_title: 'Return',
//       overview:
//         'A young couple purchase their new home to start a life together, only to find out the elderly couple next door have other plans for them.',
//       popularity: 4.191,
//       poster_path: null,
//       release_date: '2015-11-28',
//       title: 'Return',
//       video: false,
//       vote_average: 6.364,
//       vote_count: 110,
//     },
//     {
//       adult: false,
//       backdrop_path: null,
//       genre_ids: [],
//       id: 464446,
//       original_language: 'en',
//       original_title: 'Return',
//       overview:
//         'A young man returns home for the weekend to discover the difficulty of juggling friends, parents, magic mushrooms and several thousand chickens.',
//       popularity: 3.96,
//       poster_path: null,
//       release_date: '2015-07-04',
//       title: 'Return',
//       video: false,
//       vote_average: 6.146,
//       vote_count: 103,
//     },
//     {
//       adult: false,
//       backdrop_path: null,
//       genre_ids: [],
//       id: 733668,
//       original_language: 'hy',
//       original_title: 'Return',
//       overview:
//         "Eyüp decides to cross mount Ararat looking for his aunt in Yerevan after following a madman's words. His aunt has also been expecting someone to come from behind this mount for many years. Eyüp cannot be sure about the woman he finds behind the blue door, whether it is his aunt or not because they can't understand each other.",
//       popularity: 1.622,
//       poster_path: null,
//       release_date: '',
//       title: 'Return',
//       video: false,
//       vote_average: 5.909,
//       vote_count: 44,
//     },
//     {
//       adult: false,
//       backdrop_path: null,
//       genre_ids: [],
//       id: 348877,
//       original_language: 'en',
//       original_title: 'Return',
//       overview:
//         "Static images of an old country house are combined with voices of the past to evocative effect. Haunting and nostalgic, 'Return' conveys the life that exists in old, abandoned places.",
//       popularity: 2.395,
//       poster_path: null,
//       release_date: '1972-07-15',
//       title: 'Return',
//       video: false,
//       vote_average: 6.245,
//       vote_count: 53,
//     },
//     {
//       adult: false,
//       backdrop_path: null,
//       genre_ids: [18, 14],
//       id: 670355,
//       original_language: 'en',
//       original_title: 'Return',
//       overview:
//         'Owen, a young man is dissatisfied with his life. He heads into the forest to escape and learns a lot during his time there.',
//       popularity: 1.727,
//       poster_path: null,
//       release_date: '2020-01-28',
//       title: 'Return',
//       video: false,
//       vote_average: 6.134,
//       vote_count: 41,
//     },
//     {
//       adult: false,
//       backdrop_path: null,
//       genre_ids: [],
//       id: 834860,
//       original_language: 'ja',
//       original_title: 'RETURN',
//       overview: '8mm work directed by Norihiko Morinaga.',
//       popularity: 1.552,
//       poster_path: '/5YOSdqwvDLxQiqqQ3KeUNt1ir1L.jpg',
//       release_date: '1985-01-01',
//       title: 'RETURN',
//       video: false,
//       vote_average: 5.952,
//       vote_count: 42,
//     },
//     {
//       adult: false,
//       backdrop_path: null,
//       genre_ids: [99],
//       id: 828508,
//       original_language: 'es',
//       original_title: 'Return',
//       overview: '',
//       popularity: 1.532,
//       poster_path: '/xWjw5JBMuce6Wv33dDUfmzVVaAL.jpg',
//       release_date: '2018-05-11',
//       title: 'Return',
//       video: false,
//       vote_average: 5.808,
//       vote_count: 39,
//     },
//     {
//       adult: false,
//       backdrop_path: null,
//       genre_ids: [16, 878],
//       id: 839321,
//       original_language: 'en',
//       original_title: 'Return',
//       overview:
//         'Polish animator Anna Błaszczyk’s humorous short—a collage of drawing, cut-out, and computer animation—was inspired by Stanisław Lem’s 1961 novel Return from the Stars, a time-paradox tale of an astronaut who returns to Earth after many years away.',
//       popularity: 1.537,
//       poster_path: null,
//       release_date: '2008-01-01',
//       title: 'Return',
//       video: false,
//       vote_average: 6.603,
//       vote_count: 34,
//     },
//     {
//       adult: false,
//       backdrop_path: null,
//       genre_ids: [],
//       id: 357953,
//       original_language: 'en',
//       original_title: 'Return',
//       overview:
//         'Return is a methodical construction of the approach of an individual towards an unseen goal, which assumes metaphorical significance. Viola moves toward the camera/viewer, pausing every few steps to ring a bell, at which point he is momentarily thrust back to his starting place, and then advanced again. Finally reaching his destination, he is taken through all of the previous stages in a single instant and returned to the source of his journey.',
//       popularity: 1.491,
//       poster_path: null,
//       release_date: '1975-09-04',
//       title: 'Return',
//       video: false,
//       vote_average: 6.197,
//       vote_count: 33,
//     },
//     {
//       adult: false,
//       backdrop_path: '/l1H7adqYhxBrBK45aKAzqm6nIVC.jpg',
//       genre_ids: [28, 16, 878],
//       id: 39103,
//       original_language: 'ja',
//       original_title: 'ドラゴンボールZ 激突!!100億パワーの戦士たち',
//       overview:
//         'Cooler has resurrected himself as a robot and is enslaving the people of New Namek. Goku and the gang must help.',
//       popularity: 63.606,
//       poster_path: '/zJn14ySh0NTZCOIReQZiWE1fkje.jpg',
//       release_date: '1992-03-07',
//       title: 'Dragon Ball Z: The Return of Cooler',
//       video: false,
//       vote_average: 6.614,
//       vote_count: 516,
//     },
//     {
//       adult: false,
//       backdrop_path: '/kISScNcyitmRWzTVu2xmNffQlof.jpg',
//       genre_ids: [27, 14, 35],
//       id: 518158,
//       original_language: 'en',
//       original_title: 'Leprechaun Returns',
//       overview:
//         'A group of unwitting sorority sisters accidentally awaken the serial-killing Leprechaun after they build a sorority house on his hunting grounds.',
//       popularity: 22.586,
//       poster_path: '/7kToQsV04Jel1ob7VJ471LDz7wD.jpg',
//       release_date: '2018-12-11',
//       title: 'Leprechaun Returns',
//       video: false,
//       vote_average: 5.9,
//       vote_count: 343,
//     },
//     {
//       adult: false,
//       backdrop_path: null,
//       genre_ids: [],
//       id: 1091834,
//       original_language: 'en',
//       original_title: 'Return',
//       overview:
//         'RETURN tells the story of a retired Green Beret who embarks on a healing journey from Montana to Vietnam. There he retraces his steps, shares his wartime experiences with his son, treats his Post-Traumatic Stress Disorder, and seeks out the mountain tribespeople he once lived with and fought alongside as a Special Forces officer.',
//       popularity: 1.337,
//       poster_path: null,
//       release_date: '',
//       title: 'Return',
//       video: false,
//       vote_average: 6.939,
//       vote_count: 33,
//     },
//     {
//       adult: false,
//       backdrop_path: '/uIbhHNUPx8KhbP6xSebvmnbm7G2.jpg',
//       genre_ids: [16, 28, 12, 878],
//       id: 38594,
//       original_language: 'ja',
//       original_title: 'ドラゴンボール オッス!帰ってきた孫悟空と仲間たち!!',
//       overview:
//         'A 35-minute Dragon Ball animated short film that premiered at the Jump Super Anime Tour in September 2008. It is the first animated Dragon Ball feature in twelve years, following the tenth anniversary film The Path to Power.',
//       popularity: 44.995,
//       poster_path: '/97jw5YTgPgFBuJAnM6LiqxSsx5X.jpg',
//       release_date: '2008-09-21',
//       title: 'Dragon Ball: Yo! Son Goku and His Friends Return!!',
//       video: false,
//       vote_average: 6.216,
//       vote_count: 232,
//     },
//     {
//       adult: false,
//       backdrop_path: '/4QLdZ2A8mkDWp2rpfgDrwmeCtUW.jpg',
//       genre_ids: [28, 12, 80],
//       id: 47971,
//       original_language: 'en',
//       original_title: 'xXx: Return of Xander Cage',
//       overview:
//         "Extreme athlete turned government operative Xander Cage comes out of self-imposed exile, thought to be long dead, and is set on a collision course with deadly alpha warrior Xiang and his team in a race to recover a sinister and seemingly unstoppable weapon known as Pandora's Box. Recruiting an all-new group of thrill-seeking cohorts, Xander finds himself enmeshed in a deadly conspiracy that points to collusion at the highest levels of world governments.",
//       popularity: 111.966,
//       poster_path: '/hba8zREJpP1AYhaXgb2oJLQeO0K.jpg',
//       release_date: '2017-01-13',
//       title: 'xXx: Return of Xander Cage',
//       video: false,
//       vote_average: 6.132,
//       vote_count: 8360,
//     },
//     {
//       adult: false,
//       backdrop_path: '/cuiJ6e6kSatyRlnCJrvJG2ElpSg.jpg',
//       genre_ids: [12, 14, 16, 18, 10751],
//       id: 15370,
//       original_language: 'ja',
//       original_title: '猫の恩返し',
//       overview:
//         "Young Haru rescues a cat from being run over, but soon learns it's no ordinary feline; it happens to be the Prince of the Cats.",
//       popularity: 37.636,
//       poster_path: '/avPMO5cnaGHgLaNiAIhy33WoQLm.jpg',
//       release_date: '2002-07-19',
//       title: 'The Cat Returns',
//       video: false,
//       vote_average: 7.183,
//       vote_count: 1640,
//     },
//   ],
//   total_pages: 93,
//   total_results: 1852,
// };

const service = new Service();

export default service;
